development:
  client_url: <%= ENV['CLIENT_URL'] || 'http://localhost:3031' %>    #'http://022d869f.ngrok.io'
  server_url: <%= ENV['SERVER_URL'] || 'http://cfb27b39.ngrok.io' %>

test:
  client_url: http://localhost:3031
  server_url: http://localhost:3032

staging:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.usreclub.com' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.usreclub.com' %>

production:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.meejia.com' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.meejia.com' %>
