development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: spot_card
  pool: 50
  username: root

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: spot_card
  pool: 50
  username: root

production:
